# Generated by Django 5.0.4 on 2024-04-05 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_text',
            new_name='pub_date',
        ),
    ]
